# Keryx Miner bootstrap package for HiveOS Custom Miner
CUSTOM_NAME=keryx-miner
CUSTOM_VERSION=0.3.2-OPoI-bootstrap-v6
CUSTOM_BUILD=6
CUSTOM_MINERBIN=keryx-miner
CUSTOM_CONFIG_FILENAME=/hive/miners/custom/keryx-miner/config.ini
CUSTOM_LOG_BASENAME=/var/log/miner/keryx-miner
WEB_PORT=3338
